[package]
name = "assembler"
description = "Assembler for LC-3 Virtual Machine, written in Rust"
version = "1.0.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.32", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
